### ISSUE TITLE
งานเราจะดำเนินต่อได้อย่างไร ถ้า Jerm Action Failed

### ISSUE THREAD

**Issue by leomotors** [ST4RCHASER/monk-action#72]
ช่วยด้วยครับ https://github.com/cunny-SHiT6/holy-prophet-launchpad

**Comment by ST4RCHASER** [comment]
ทางเรารับทราบถึงปัญหานี้แล้วและได้ทำการให้ monk ของเรานั้นไปเรียนเพิ่มในหลักสูตรมนต์ `try catch` จนตอนนี้สามารถรับมือได้แล้ว 🙏🙏

อ้างอิง: https://github.com/ST4RCHASER/jerm-action/commit/5d63693506b6cda7c809df8e1ca0d8040a58bdaa
